name: Build and Deploy on Tag Push

on:
  push:
    tags:
      - 'v*' # Only trigger on version tags like v1.0.0
  # Optional: Also run on main/dev branch commits
  # push:
  #   branches:
  #     - main
  #     - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy project
        run: npm run deploy
